services:

  app:
    build: .
    ports:
      - "80:8000"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro        # accès aux infos système Linux
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # config scraping
      - prometheus-data:/prometheus                       # persistance des métriques
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8080:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin   # mot de passe Grafana
    volumes:
      - grafana-data:/var/lib/grafana      # persistance des dashboards
    networks:
      - monitoring

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge